//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidiBard.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MidiBard.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} track in playlist. 的本地化字符串。
        /// </summary>
        internal static string _0__track_in_playlist_ {
            get {
                return ResourceManager.GetString("{0} track in playlist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} tracks in current playlist. 的本地化字符串。
        /// </summary>
        internal static string _0__tracks_in_playlist_ {
            get {
                return ResourceManager.GetString("{0} tracks in playlist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto adapt notes 的本地化字符串。
        /// </summary>
        internal static string Auto_adapt_notes {
            get {
                return ResourceManager.GetString("Auto adapt notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adapt high/low pitch notes which are out of range into 3 octaves we can play 的本地化字符串。
        /// </summary>
        internal static string Auto_adapt_notesTooltip {
            get {
                return ResourceManager.GetString("Auto adapt notesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Confirm Ensemble Ready Check 的本地化字符串。
        /// </summary>
        internal static string Auto_Confirm_Ensemble_Ready_Check {
            get {
                return ResourceManager.GetString("Auto Confirm Ensemble Ready Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto open MidiBard 的本地化字符串。
        /// </summary>
        internal static string Auto_open_MidiBard {
            get {
                return ResourceManager.GetString("Auto open MidiBard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto open or close MidiBard window when entering/exiting performance mode 的本地化字符串。
        /// </summary>
        internal static string Auto_open_MidiBardTooltip {
            get {
                return ResourceManager.GetString("Auto open MidiBardTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto set background frame limit 的本地化字符串。
        /// </summary>
        internal static string Auto_set_background_frame_limit {
            get {
                return ResourceManager.GetString("Auto set background frame limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto disable background frame limit when entering performance mode and re-enable it when quit performance 的本地化字符串。
        /// </summary>
        internal static string Auto_set_frame_limit_tooltip {
            get {
                return ResourceManager.GetString("Auto set frame limit tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto switch instrument 的本地化字符串。
        /// </summary>
        internal static string Auto_switch_instrument {
            get {
                return ResourceManager.GetString("Auto switch instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto switch instrument on demand. If you need this, 
        ///please add #instrument name# before file name. 
        ///E.g. #harp#demo.mid 的本地化字符串。
        /// </summary>
        internal static string Auto_switch_instrumentTooltip {
            get {
                return ResourceManager.GetString("Auto switch instrumentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto transpose 的本地化字符串。
        /// </summary>
        internal static string Auto_transpose {
            get {
                return ResourceManager.GetString("Auto transpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto transpose notes on demand. If you need this, 
        ///please add #transpose number# before file name. 
        ///E.g. #-12#demo.mid 的本地化字符串。
        /// </summary>
        internal static string Auto_transpose_notesTooltip {
            get {
                return ResourceManager.GetString("Auto transpose notesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Begin ensemble ready check 的本地化字符串。
        /// </summary>
        internal static string Begin_ensemble_ready_check {
            get {
                return ResourceManager.GetString("Begin ensemble ready check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Playlist 的本地化字符串。
        /// </summary>
        internal static string button_clear_playlist {
            get {
                return ResourceManager.GetString("button clear playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double click to clear playlist 的本地化字符串。
        /// </summary>
        internal static string button_clearplaylist_tootltip {
            get {
                return ResourceManager.GetString("button clearplaylist tootltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ensemble panel 的本地化字符串。
        /// </summary>
        internal static string button_ensemble_panel {
            get {
                return ResourceManager.GetString("button ensemble panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import midi file
        ///Right click to select file dialog type 的本地化字符串。
        /// </summary>
        internal static string button_import_file {
            get {
                return ResourceManager.GetString("button import file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import folder
        ///Imports all midi files in selected folder and it&apos;s all subfolders.
        ///This may take a while when you select a folder that contains multiple layers of folders. 的本地化字符串。
        /// </summary>
        internal static string button_import_folder {
            get {
                return ResourceManager.GetString("button import folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mini player 的本地化字符串。
        /// </summary>
        internal static string button_mini_player {
            get {
                return ResourceManager.GetString("button mini player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show playlist selector 的本地化字符串。
        /// </summary>
        internal static string button_show_playlist_selector {
            get {
                return ResourceManager.GetString("button show playlist selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change UI Language 的本地化字符串。
        /// </summary>
        internal static string Change_UI_Language {
            get {
                return ResourceManager.GetString("Change UI Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto restart listening 的本地化字符串。
        /// </summary>
        internal static string checkbox_auto_restart_listening {
            get {
                return ResourceManager.GetString("checkbox auto restart listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try auto restart listening last used midi device 的本地化字符串。
        /// </summary>
        internal static string checkbox_auto_restart_listening_tooltip {
            get {
                return ResourceManager.GetString("checkbox auto restart listening tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clone current playlist 的本地化字符串。
        /// </summary>
        internal static string Clone_current_playlist {
            get {
                return ResourceManager.GetString("Clone current playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double click to delete current playlist 的本地化字符串。
        /// </summary>
        internal static string delete_current_playlist {
            get {
                return ResourceManager.GetString("delete current playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign track to a character. Right click to reset assigned character 的本地化字符串。
        /// </summary>
        internal static string ensemble_assign_track_character_tooltip {
            get {
                return ResourceManager.GetString("ensemble assign track character tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw ensemble progress indicator on visualizer 的本地化字符串。
        /// </summary>
        internal static string ensemble_config_Draw_ensemble_progress_indicator_on_visualizer {
            get {
                return ResourceManager.GetString("ensemble config Draw ensemble progress indicator on visualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ensemble indicator delay 的本地化字符串。
        /// </summary>
        internal static string ensemble_config_Ensemble_indicator_delay {
            get {
                return ResourceManager.GetString("ensemble config Ensemble indicator delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update instrument when begin ensemble 的本地化字符串。
        /// </summary>
        internal static string ensemble_config_Update_instrument_when_begin_ensemble {
            get {
                return ResourceManager.GetString("ensemble config Update instrument when begin ensemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete and reset current file config 的本地化字符串。
        /// </summary>
        internal static string ensemble_Delete_and_reset_current_file_config {
            get {
                return ResourceManager.GetString("ensemble Delete and reset current file config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize other clients, right click to restore them. 的本地化字符串。
        /// </summary>
        internal static string ensemble_Minimize_other_clients {
            get {
                return ResourceManager.GetString("ensemble Minimize other clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mute other clients 的本地化字符串。
        /// </summary>
        internal static string ensemble_mute_other_clients {
            get {
                return ResourceManager.GetString("ensemble mute other clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open current midi config file directory 的本地化字符串。
        /// </summary>
        internal static string ensemble_open_midi_config_directory {
            get {
                return ResourceManager.GetString("ensemble open midi config directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open current midi config file 的本地化字符串。
        /// </summary>
        internal static string ensemble_open_midi_config_file {
            get {
                return ResourceManager.GetString("ensemble open midi config file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save default performers 的本地化字符串。
        /// </summary>
        internal static string ensemble_Save_default_performers {
            get {
                return ResourceManager.GetString("ensemble Save default performers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a song from playlist 的本地化字符串。
        /// </summary>
        internal static string ensemble_Select_a_song_from_playlist {
            get {
                return ResourceManager.GetString("ensemble Select a song from playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync all Midibard settings on this pc 的本地化字符串。
        /// </summary>
        internal static string ensemble_Sync_settings {
            get {
                return ResourceManager.GetString("ensemble Sync settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unmute other clients 的本地化字符串。
        /// </summary>
        internal static string ensemble_unmute_other_clients {
            get {
                return ResourceManager.GetString("ensemble unmute other clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Instruments, right click to pull back instrument 的本地化字符串。
        /// </summary>
        internal static string ensemble_update_instruments {
            get {
                return ResourceManager.GetString("ensemble update instruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MidiBard local ensemble control 的本地化字符串。
        /// </summary>
        internal static string ensemble_window_title {
            get {
                return ResourceManager.GetString("ensemble window title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow playback 的本地化字符串。
        /// </summary>
        internal static string Follow_playback {
            get {
                return ResourceManager.GetString("Follow playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock tracks window and auto following current playback progress 的本地化字符串。
        /// </summary>
        internal static string Follow_playback_tooltip {
            get {
                return ResourceManager.GetString("Follow playback tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter to search 的本地化字符串。
        /// </summary>
        internal static string hint_search_textbox {
            get {
                return ResourceManager.GetString("hint search textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImGui file dialog 的本地化字符串。
        /// </summary>
        internal static string imgui_file_dialog {
            get {
                return ResourceManager.GetString("imgui file dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import in progress... 的本地化字符串。
        /// </summary>
        internal static string Import_in_progress___ {
            get {
                return ResourceManager.GetString("Import in progress...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instrument 的本地化字符串。
        /// </summary>
        internal static string Instrument {
            get {
                return ResourceManager.GetString("Instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto switch instrument by midi track name 的本地化字符串。
        /// </summary>
        internal static string label_auto_switch_instrument_bmp {
            get {
                return ResourceManager.GetString("label auto switch instrument bmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transpose/switch instrument based on first enabled midi track name. 的本地化字符串。
        /// </summary>
        internal static string label_auto_switch_instrument_bmp_tooltip {
            get {
                return ResourceManager.GetString("label auto switch instrument bmp tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay 的本地化字符串。
        /// </summary>
        internal static string label_delay {
            get {
                return ResourceManager.GetString("label delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay time before play next track. 的本地化字符串。
        /// </summary>
        internal static string label_delay_tooltip {
            get {
                return ResourceManager.GetString("label delay tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import midi files to start performing! 的本地化字符串。
        /// </summary>
        internal static string label_empty_playlist {
            get {
                return ResourceManager.GetString("label empty playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ensemble Mode Running 的本地化字符串。
        /// </summary>
        internal static string label_ensemble_mode_running {
            get {
                return ResourceManager.GetString("label ensemble mode running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string label_Help {
            get {
                return ResourceManager.GetString("label Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Device 的本地化字符串。
        /// </summary>
        internal static string label_inputdevice {
            get {
                return ResourceManager.GetString("label inputdevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose external midi input device. right click to reset. 的本地化字符串。
        /// </summary>
        internal static string label_inputdevice_tooltip {
            get {
                return ResourceManager.GetString("label inputdevice tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string label_language {
            get {
                return ResourceManager.GetString("label language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search playlist 的本地化字符串。
        /// </summary>
        internal static string label_search_playlist {
            get {
                return ResourceManager.GetString("label search playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme color 的本地化字符串。
        /// </summary>
        internal static string label_theme_color {
            get {
                return ResourceManager.GetString("label theme color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transpose per track 的本地化字符串。
        /// </summary>
        internal static string label_transpose_by_track {
            get {
                return ResourceManager.GetString("label transpose by track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transpose per track, right click to reset all tracks&apos; transpose offset back to zero. 的本地化字符串。
        /// </summary>
        internal static string label_transpose_by_track_tootltip {
            get {
                return ResourceManager.GetString("label transpose by track tootltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listening input device:  的本地化字符串。
        /// </summary>
        internal static string listenning_midi_device_banner {
            get {
                return ResourceManager.GetString("listenning midi device banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ListOrdered 的本地化字符串。
        /// </summary>
        internal static string ListOrdered {
            get {
                return ResourceManager.GetString("ListOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ListRepeat 的本地化字符串。
        /// </summary>
        internal static string ListRepeat {
            get {
                return ResourceManager.GetString("ListRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low latency mode 的本地化字符串。
        /// </summary>
        internal static string Low_latency_mode {
            get {
                return ResourceManager.GetString("Low latency mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use alternative note input method, May slightly reduce input latency but will affect guitar tone switching accuracy. 
        ///Only recommended while using Midi keyboard. 的本地化字符串。
        /// </summary>
        internal static string low_latency_mode_tooltip {
            get {
                return ResourceManager.GetString("low latency mode tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor ensemble 的本地化字符串。
        /// </summary>
        internal static string Monitor_ensemble {
            get {
                return ResourceManager.GetString("Monitor ensemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto start ensemble when entering in-game party ensemble mode 的本地化字符串。
        /// </summary>
        internal static string Monitor_ensemble_tooltip {
            get {
                return ResourceManager.GetString("Monitor ensemble tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Music control panel 的本地化字符串。
        /// </summary>
        internal static string Music_control_panel {
            get {
                return ResourceManager.GetString("Music control panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New playlist 的本地化字符串。
        /// </summary>
        internal static string New_playlist {
            get {
                return ResourceManager.GetString("New playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; is not available now.
        ///Please check log for further error information. 的本地化字符串。
        /// </summary>
        internal static string notice_midi_device_error {
            get {
                return ResourceManager.GetString("notice midi device error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop event listening on  的本地化字符串。
        /// </summary>
        internal static string notice_midi_device_stop_listening {
            get {
                return ResourceManager.GetString("notice midi device stop listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start event listening on  的本地化字符串。
        /// </summary>
        internal static string notice_start_event_listening {
            get {
                return ResourceManager.GetString("notice start event listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playing: 的本地化字符串。
        /// </summary>
        internal static string Playing_ {
            get {
                return ResourceManager.GetString("Playing:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MidiBard Playlist 的本地化字符串。
        /// </summary>
        internal static string playlist_window_title {
            get {
                return ResourceManager.GetString("playlist window title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playmode:  的本地化字符串。
        /// </summary>
        internal static string Playmode_ {
            get {
                return ResourceManager.GetString("Playmode:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single 的本地化字符串。
        /// </summary>
        internal static string Playmode_Single {
            get {
                return ResourceManager.GetString("Playmode_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PlaySpeed 的本地化字符串。
        /// </summary>
        internal static string PlaySpeed {
            get {
                return ResourceManager.GetString("PlaySpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress 的本地化字符串。
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random 的本地化字符串。
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save and sync 的本地化字符串。
        /// </summary>
        internal static string Save_and_sync {
            get {
                return ResourceManager.GetString("Save and sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save current search result as new playlist 的本地化字符串。
        /// </summary>
        internal static string Save_search_as_playlist {
            get {
                return ResourceManager.GetString("Save search as playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select current instrument 
        ///Right click to quit performance mode 的本地化字符串。
        /// </summary>
        internal static string select_instrument_tooltip {
            get {
                return ResourceManager.GetString("select instrument tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the playing progress 
        ///Right click to restart current playback 的本地化字符串。
        /// </summary>
        internal static string Set_progress_tooltip {
            get {
                return ResourceManager.GetString("Set progress tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the speed of events playing 的本地化字符串。
        /// </summary>
        internal static string Set_speed_tooltip {
            get {
                return ResourceManager.GetString("Set speed tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings panel 的本地化字符串。
        /// </summary>
        internal static string Settings_panel {
            get {
                return ResourceManager.GetString("Settings panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SingleRepeat 的本地化字符串。
        /// </summary>
        internal static string SingleRepeat {
            get {
                return ResourceManager.GetString("SingleRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standalone playlist window 的本地化字符串。
        /// </summary>
        internal static string Standalone_playlist_window {
            get {
                return ResourceManager.GetString("Standalone playlist window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop ensemble 的本地化字符串。
        /// </summary>
        internal static string Stop_ensemble {
            get {
                return ResourceManager.GetString("Stop ensemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tone mode 的本地化字符串。
        /// </summary>
        internal static string tone_mode {
            get {
                return ResourceManager.GetString("tone mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string tone_mode_off {
            get {
                return ResourceManager.GetString("tone mode off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off: Does not take over game&apos;s guitar tone control. 的本地化字符串。
        /// </summary>
        internal static string tone_mode_off_tooltip {
            get {
                return ResourceManager.GetString("tone mode off tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Override 的本地化字符串。
        /// </summary>
        internal static string tone_mode_override {
            get {
                return ResourceManager.GetString("tone mode override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Override by track: Assign guitar tone manually for each track and ignore ProgramChange events. 的本地化字符串。
        /// </summary>
        internal static string tone_mode_override_tooltip {
            get {
                return ResourceManager.GetString("tone mode override tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple 的本地化字符串。
        /// </summary>
        internal static string tone_mode_simple {
            get {
                return ResourceManager.GetString("tone mode simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple: Simple ProgramChange handling, ProgramChange event on any channel will change all channels&apos; program state. (This is BardMusicPlayer&apos;s default behavior.) 的本地化字符串。
        /// </summary>
        internal static string tone_mode_simple_tooltip {
            get {
                return ResourceManager.GetString("tone mode simple tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard 的本地化字符串。
        /// </summary>
        internal static string tone_mode_standard {
            get {
                return ResourceManager.GetString("tone mode standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard: Standard midi channel and ProgramChange handling, each channel will keep it&apos;s program state separately. 的本地化字符串。
        /// </summary>
        internal static string tone_mode_standard_tooltip {
            get {
                return ResourceManager.GetString("tone mode standard tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose how MidiBard will handle MIDI channels and ProgramChange events(current only affects guitar tone changing) 的本地化字符串。
        /// </summary>
        internal static string tone_mode_tooltip {
            get {
                return ResourceManager.GetString("tone mode tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Track 的本地化字符串。
        /// </summary>
        internal static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Track Selection
        ///MidiBard will only perform enabled tracks
        ///Left click to enable/disable a track, Right click to solo it 的本地化字符串。
        /// </summary>
        internal static string Track_selection_Tooltip {
            get {
                return ResourceManager.GetString("Track selection Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transpose 的本地化字符串。
        /// </summary>
        internal static string Transpose {
            get {
                return ResourceManager.GetString("Transpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transpose, measured by semitone. 
        ///Right click to reset. 的本地化字符串。
        /// </summary>
        internal static string TransposeTooltip {
            get {
                return ResourceManager.GetString("TransposeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tracks visualization 的本地化字符串。
        /// </summary>
        internal static string visualization {
            get {
                return ResourceManager.GetString("visualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right click to reset visualizer window position. 的本地化字符串。
        /// </summary>
        internal static string visualization_tooltip {
            get {
                return ResourceManager.GetString("visualization tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Win32 file dialog 的本地化字符串。
        /// </summary>
        internal static string w32_file_dialog {
            get {
                return ResourceManager.GetString("w32 file dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MidiBard track visualizer 的本地化字符串。
        /// </summary>
        internal static string window_title_visualizor {
            get {
                return ResourceManager.GetString("window title visualizor", resourceCulture);
            }
        }
    }
}
