//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidiBard.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MidiBard.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Begin ensemble ready check 的本地化字符串。
        /// </summary>
        internal static string ensemble_begin_ensemble_ready_check {
            get {
                return ResourceManager.GetString("ensemble begin ensemble ready check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign track to a character. Right click to reset assigned character 的本地化字符串。
        /// </summary>
        internal static string ensemble_combo_tooltip_assign_track_character {
            get {
                return ResourceManager.GetString("ensemble combo tooltip assign track character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw ensemble progress indicator on visualizer 的本地化字符串。
        /// </summary>
        internal static string ensemble_config_Draw_ensemble_progress_indicator_on_visualizer {
            get {
                return ResourceManager.GetString("ensemble config Draw ensemble progress indicator on visualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ensemble indicator delay 的本地化字符串。
        /// </summary>
        internal static string ensemble_config_Ensemble_indicator_delay {
            get {
                return ResourceManager.GetString("ensemble config Ensemble indicator delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update instrument when begin ensemble 的本地化字符串。
        /// </summary>
        internal static string ensemble_config_Update_instrument_when_begin_ensemble {
            get {
                return ResourceManager.GetString("ensemble config Update instrument when begin ensemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete and reset current file config 的本地化字符串。
        /// </summary>
        internal static string ensemble_Delete_and_reset_current_file_config {
            get {
                return ResourceManager.GetString("ensemble Delete and reset current file config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize other clients, right click to restore them. 的本地化字符串。
        /// </summary>
        internal static string ensemble_Minimize_other_clients {
            get {
                return ResourceManager.GetString("ensemble Minimize other clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mute other clients 的本地化字符串。
        /// </summary>
        internal static string ensemble_mute_other_clients {
            get {
                return ResourceManager.GetString("ensemble mute other clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open current midi config file directory 的本地化字符串。
        /// </summary>
        internal static string ensemble_open_midi_config_directory {
            get {
                return ResourceManager.GetString("ensemble open midi config directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open current midi config file 的本地化字符串。
        /// </summary>
        internal static string ensemble_open_midi_config_file {
            get {
                return ResourceManager.GetString("ensemble open midi config file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save default performers 的本地化字符串。
        /// </summary>
        internal static string ensemble_Save_default_performers {
            get {
                return ResourceManager.GetString("ensemble Save default performers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a song from playlist 的本地化字符串。
        /// </summary>
        internal static string ensemble_Select_a_song_from_playlist {
            get {
                return ResourceManager.GetString("ensemble Select a song from playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop ensemble 的本地化字符串。
        /// </summary>
        internal static string ensemble_stop_ensemble {
            get {
                return ResourceManager.GetString("ensemble stop ensemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unmute other clients 的本地化字符串。
        /// </summary>
        internal static string ensemble_unmute_other_clients {
            get {
                return ResourceManager.GetString("ensemble unmute other clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Instruments, right click to pull back instrument 的本地化字符串。
        /// </summary>
        internal static string ensemble_update_instruments {
            get {
                return ResourceManager.GetString("ensemble update instruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter to search 的本地化字符串。
        /// </summary>
        internal static string hint_search_textbox {
            get {
                return ResourceManager.GetString("hint search textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Playlist 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_clear_playlist {
            get {
                return ResourceManager.GetString("icon button tooltip clear playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double click to clear playlist 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_clearplaylist_tootltip {
            get {
                return ResourceManager.GetString("icon button tooltip clearplaylist tootltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clone current playlist 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_clone_current_playlist {
            get {
                return ResourceManager.GetString("icon button tooltip clone current playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double click to delete current playlist 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_delete_current_playlist {
            get {
                return ResourceManager.GetString("icon button tooltip delete current playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ensemble panel 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_ensemble_panel {
            get {
                return ResourceManager.GetString("icon button tooltip ensemble panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_help {
            get {
                return ResourceManager.GetString("icon button tooltip help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import midi file
        ///Right click to select file dialog type 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_import_file {
            get {
                return ResourceManager.GetString("icon button tooltip import file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import folder
        ///Imports all midi files in selected folder and it&apos;s all subfolders.
        ///This may take a while when you select a folder that contains multiple layers of folders. 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_import_folder {
            get {
                return ResourceManager.GetString("icon button tooltip import folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mini player 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_mini_player {
            get {
                return ResourceManager.GetString("icon button tooltip mini player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Music control panel 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_music_control_panel {
            get {
                return ResourceManager.GetString("icon button tooltip music control panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New playlist 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_new_playlist {
            get {
                return ResourceManager.GetString("icon button tooltip new playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save and sync 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_save_and_sync_playlist {
            get {
                return ResourceManager.GetString("icon button tooltip save and sync playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save current search result as new playlist 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_save_search_as_playlist {
            get {
                return ResourceManager.GetString("icon button tooltip save search as playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search playlist 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_search_playlist {
            get {
                return ResourceManager.GetString("icon button tooltip search playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings panel 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_settings_panel {
            get {
                return ResourceManager.GetString("icon button tooltip settings panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show playlist selector 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_show_playlist_selector {
            get {
                return ResourceManager.GetString("icon button tooltip show playlist selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync all Midibard settings on this pc 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_sync_settings {
            get {
                return ResourceManager.GetString("icon button tooltip sync settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tracks visualization window
        ///Right click to reset visualizer window position 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_visualization {
            get {
                return ResourceManager.GetString("icon button tooltip visualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Following current playback progress 的本地化字符串。
        /// </summary>
        internal static string icon_button_tooltip_visualizer_follow_playback_tooltip {
            get {
                return ResourceManager.GetString("icon button tooltip visualizer follow playback tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImGui file dialog 的本地化字符串。
        /// </summary>
        internal static string imgui_file_dialog {
            get {
                return ResourceManager.GetString("imgui file dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; is not available now.
        ///Please check log for further error information. 的本地化字符串。
        /// </summary>
        internal static string notice_midi_device_error {
            get {
                return ResourceManager.GetString("notice midi device error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop event listening on  的本地化字符串。
        /// </summary>
        internal static string notice_midi_device_stop_listening {
            get {
                return ResourceManager.GetString("notice midi device stop listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List ordered 的本地化字符串。
        /// </summary>
        internal static string play_mode_list_ordered {
            get {
                return ResourceManager.GetString("play mode list ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List repeat 的本地化字符串。
        /// </summary>
        internal static string play_mode_list_repeat {
            get {
                return ResourceManager.GetString("play mode list repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random 的本地化字符串。
        /// </summary>
        internal static string play_mode_random {
            get {
                return ResourceManager.GetString("play mode random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single 的本地化字符串。
        /// </summary>
        internal static string play_mode_single {
            get {
                return ResourceManager.GetString("play mode single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single repeat 的本地化字符串。
        /// </summary>
        internal static string play_mode_single_repeat {
            get {
                return ResourceManager.GetString("play mode single repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ensemble settings 的本地化字符串。
        /// </summary>
        internal static string setting_group_label_ensemble_settings {
            get {
                return ResourceManager.GetString("setting group label ensemble settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General settings 的本地化字符串。
        /// </summary>
        internal static string setting_group_label_general_settings {
            get {
                return ResourceManager.GetString("setting group label general settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performance settings 的本地化字符串。
        /// </summary>
        internal static string setting_group_label_performance_settings {
            get {
                return ResourceManager.GetString("setting group label performance settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto adapt notes 的本地化字符串。
        /// </summary>
        internal static string setting_label_auto_adapt_notes {
            get {
                return ResourceManager.GetString("setting label auto adapt notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto open MidiBard 的本地化字符串。
        /// </summary>
        internal static string setting_label_auto_open_MidiBard {
            get {
                return ResourceManager.GetString("setting label auto open MidiBard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto restart listening 的本地化字符串。
        /// </summary>
        internal static string setting_label_auto_restart_listening {
            get {
                return ResourceManager.GetString("setting label auto restart listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto set background frame limit 的本地化字符串。
        /// </summary>
        internal static string setting_label_auto_set_background_frame_limit {
            get {
                return ResourceManager.GetString("setting label auto set background frame limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto switch instrument(midi track name) 的本地化字符串。
        /// </summary>
        internal static string setting_label_auto_switch_instrument_bmp {
            get {
                return ResourceManager.GetString("setting label auto switch instrument bmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto switch instrument(file name) 的本地化字符串。
        /// </summary>
        internal static string setting_label_auto_switch_instrument_by_file_name {
            get {
                return ResourceManager.GetString("setting label auto switch instrument by file name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto transpose(file name) 的本地化字符串。
        /// </summary>
        internal static string setting_label_auto_transpose_by_file_name {
            get {
                return ResourceManager.GetString("setting label auto transpose by file name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low latency mode 的本地化字符串。
        /// </summary>
        internal static string setting_label_low_latency_mode {
            get {
                return ResourceManager.GetString("setting label low latency mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI Input 的本地化字符串。
        /// </summary>
        internal static string setting_label_midi_input_device {
            get {
                return ResourceManager.GetString("setting label midi input device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor ensemble 的本地化字符串。
        /// </summary>
        internal static string setting_label_monitor_ensemble {
            get {
                return ResourceManager.GetString("setting label monitor ensemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instrument 的本地化字符串。
        /// </summary>
        internal static string setting_label_select_instrument {
            get {
                return ResourceManager.GetString("setting label select instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string setting_label_select_ui_language {
            get {
                return ResourceManager.GetString("setting label select ui language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play speed 的本地化字符串。
        /// </summary>
        internal static string setting_label_set_play_speed {
            get {
                return ResourceManager.GetString("setting label set play speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress 的本地化字符串。
        /// </summary>
        internal static string setting_label_set_progress {
            get {
                return ResourceManager.GetString("setting label set progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay 的本地化字符串。
        /// </summary>
        internal static string setting_label_song_delay {
            get {
                return ResourceManager.GetString("setting label song delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standalone playlist window 的本地化字符串。
        /// </summary>
        internal static string setting_label_standalone_playlist_window {
            get {
                return ResourceManager.GetString("setting label standalone playlist window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable local clients sync 的本地化字符串。
        /// </summary>
        internal static string setting_label_sync_clients {
            get {
                return ResourceManager.GetString("setting label sync clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI color 的本地化字符串。
        /// </summary>
        internal static string setting_label_theme_color {
            get {
                return ResourceManager.GetString("setting label theme color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tone mode 的本地化字符串。
        /// </summary>
        internal static string setting_label_tone_mode {
            get {
                return ResourceManager.GetString("setting label tone mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transpose 的本地化字符串。
        /// </summary>
        internal static string setting_label_transpose_all {
            get {
                return ResourceManager.GetString("setting label transpose all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transpose per track 的本地化字符串。
        /// </summary>
        internal static string setting_label_transpose_by_track {
            get {
                return ResourceManager.GetString("setting label transpose by track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adapt high/low pitch notes when they are out of range into 3 octaves we can play 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_auto_adapt_notes {
            get {
                return ResourceManager.GetString("setting tooltip auto adapt notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto open or close MidiBard window when entering/exiting performance mode 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_auto_open_MidiBardTooltip {
            get {
                return ResourceManager.GetString("setting tooltip auto open MidiBardTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try auto restart listening last used midi device 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_auto_restart_listening {
            get {
                return ResourceManager.GetString("setting tooltip auto restart listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto disable background frame limit when entering performance mode and re-enable it when quit performance 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_auto_set_background_frame_limit {
            get {
                return ResourceManager.GetString("setting tooltip auto set background frame limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transpose/switch instrument based on first enabled midi track name(BMP rules) 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_auto_switch_transpose_instrument_bmp_trackname {
            get {
                return ResourceManager.GetString("setting tooltip auto switch transpose instrument bmp trackname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto transpose notes on demand. If you need this, 
        ///please add #transpose number# before file name. 
        ///E.g. #-12#demo.mid 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_auto_transpose_by_file_name {
            get {
                return ResourceManager.GetString("setting tooltip auto transpose by file name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto switch instrument on demand. If you need this, 
        ///please add #instrument name# before file name. 
        ///E.g. #harp#demo.mid 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_label_auto_switch_instrument_by_file_name {
            get {
                return ResourceManager.GetString("setting tooltip label auto switch instrument by file name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Midibard UI language 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_language {
            get {
                return ResourceManager.GetString("setting tooltip language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use alternative note input method, May slightly reduce input latency but will affect guitar tone switching accuracy. 
        ///Only recommended while using Midi keyboard. 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_low_latency_mode {
            get {
                return ResourceManager.GetString("setting tooltip low latency mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto start ensemble when entering in-game party ensemble mode 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_monitor_ensemble {
            get {
                return ResourceManager.GetString("setting tooltip monitor ensemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose external midi input device. Right click to reset. 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_select_input_device {
            get {
                return ResourceManager.GetString("setting tooltip select input device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select current instrument 
        ///Right click to quit performance mode 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_select_instrument {
            get {
                return ResourceManager.GetString("setting tooltip select instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the playing progress 
        ///Right click to restart current playback 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_set_progress {
            get {
                return ResourceManager.GetString("setting tooltip set progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the speed of events playing 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_set_speed {
            get {
                return ResourceManager.GetString("setting tooltip set speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay time before play next track. 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_song_delay {
            get {
                return ResourceManager.GetString("setting tooltip song delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow midibard settings and midi file settings auto sync between all midibard instances on this pc 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_sync_clients {
            get {
                return ResourceManager.GetString("setting tooltip sync clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose how MidiBard will handle MIDI channels and ProgramChange events(current only affects guitar tone changing) 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_tone_mode {
            get {
                return ResourceManager.GetString("setting tooltip tone mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transpose, measured by semitone. 
        ///Right click to reset. 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_transpose_all {
            get {
                return ResourceManager.GetString("setting tooltip transpose all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transpose per track, right click to reset all tracks&apos; transpose offset back to zero. 的本地化字符串。
        /// </summary>
        internal static string setting_tooltip_transpose_by_track {
            get {
                return ResourceManager.GetString("setting tooltip transpose by track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playing: 的本地化字符串。
        /// </summary>
        internal static string text_current_playing {
            get {
                return ResourceManager.GetString("text current playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ensemble mode running 的本地化字符串。
        /// </summary>
        internal static string text_ensemble_mode_running {
            get {
                return ResourceManager.GetString("text ensemble mode running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import in progress... 的本地化字符串。
        /// </summary>
        internal static string text_Import_in_progress {
            get {
                return ResourceManager.GetString("text Import in progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listening input device:  的本地化字符串。
        /// </summary>
        internal static string text_listening_midi_device {
            get {
                return ResourceManager.GetString("text listening midi device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import midi files to start performing! 的本地化字符串。
        /// </summary>
        internal static string text_playlist_is_empty {
            get {
                return ResourceManager.GetString("text playlist is empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playmode:  的本地化字符串。
        /// </summary>
        internal static string text_select_playmode {
            get {
                return ResourceManager.GetString("text select playmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start event listening on  的本地化字符串。
        /// </summary>
        internal static string text_start_event_listening {
            get {
                return ResourceManager.GetString("text start event listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} tracks in current playlist. 的本地化字符串。
        /// </summary>
        internal static string text_tracks_in_playlist {
            get {
                return ResourceManager.GetString("text tracks in playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string tone_mode_off {
            get {
                return ResourceManager.GetString("tone mode off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off: Does not take over game&apos;s guitar tone control. 的本地化字符串。
        /// </summary>
        internal static string tone_mode_off_tooltip {
            get {
                return ResourceManager.GetString("tone mode off tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Override 的本地化字符串。
        /// </summary>
        internal static string tone_mode_override {
            get {
                return ResourceManager.GetString("tone mode override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Override by track: Assign guitar tone manually for each track and ignore ProgramChange events. 的本地化字符串。
        /// </summary>
        internal static string tone_mode_override_tooltip {
            get {
                return ResourceManager.GetString("tone mode override tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple 的本地化字符串。
        /// </summary>
        internal static string tone_mode_simple {
            get {
                return ResourceManager.GetString("tone mode simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple: Simple ProgramChange handling, ProgramChange event on any channel will change all channels&apos; program state. (This is BardMusicPlayer&apos;s default behavior.) 的本地化字符串。
        /// </summary>
        internal static string tone_mode_simple_tooltip {
            get {
                return ResourceManager.GetString("tone mode simple tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard 的本地化字符串。
        /// </summary>
        internal static string tone_mode_standard {
            get {
                return ResourceManager.GetString("tone mode standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard: Standard midi channel and ProgramChange handling, each channel will keep it&apos;s program state separately. 的本地化字符串。
        /// </summary>
        internal static string tone_mode_standard_tooltip {
            get {
                return ResourceManager.GetString("tone mode standard tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Win32 file dialog 的本地化字符串。
        /// </summary>
        internal static string w32_file_dialog {
            get {
                return ResourceManager.GetString("w32 file dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MidiBard local ensemble control 的本地化字符串。
        /// </summary>
        internal static string window_title_ensemble_panel {
            get {
                return ResourceManager.GetString("window title ensemble panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MidiBard Playlist 的本地化字符串。
        /// </summary>
        internal static string window_title_standalone_playlist {
            get {
                return ResourceManager.GetString("window title standalone playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MidiBard track visualizer 的本地化字符串。
        /// </summary>
        internal static string window_title_visualizor {
            get {
                return ResourceManager.GetString("window title visualizor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Track selection
        ///MidiBard will only perform enabled tracks
        ///Left click to enable/disable a track, Right click to solo it 的本地化字符串。
        /// </summary>
        internal static string window_tooltip_track_selection {
            get {
                return ResourceManager.GetString("window tooltip track selection", resourceCulture);
            }
        }
    }
}
